[build]
  command = "yarn build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[template]
  incoming-hooks = ["DatoCMS"]
[template.environment]
  NEXT_PUBLIC_DATO_KEY="change me for your secret token"
  SITE_URL="set the url to your netlify site for sitemap here"
